### ISSUE TITLE
打包vue组件时报错，求助

### ISSUE THREAD

**Issue by SyanH** [moonrailgun/mini-star#20]
已经配置了.ministarrc.js中rollup-plugin-vue插件
```
const vuePlugin = require('rollup-plugin-vue')

module.exports = {
	scope: 'plugins',
	pluginRoot: './src',
	outDir: './dist',
	externalDeps: [],
	rollupPlugins: [
		vuePlugin({
			css: true,
      		compileTemplate: true
		})
	]
}
```

但是build时，会报以下错误：像是无法解析<template>这样的标签
```
✖ Bundle [test] error
Error: Transform failed with 1 error:
/Users/syan/Work/FroutEnd/scui/src/plugins/test/src/views/test.vue?vue&type=template&id=1f9c2b83&lang.js:2:1: error: Unexpected "<"
    at failureErrorWithLog (/Users/syan/Work/FroutEnd/scui/node_modules/esbuild/lib/main.js:1451:15)
    at /Users/syan/Work/FroutEnd/scui/node_modules/esbuild/lib/main.js:1262:29
    at /Users/syan/Work/FroutEnd/scui/node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (/Users/syan/Work/FroutEnd/scui/node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (/Users/syan/Work/FroutEnd/scui/node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (node:events:378:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Unexpected "<"'
    }
  ],
  warnings: [],
  code: 'PLUGIN_ERROR',
  plugin: 'esbuild',
  hook: 'transform',
  id: '/Users/syan/Work/FroutEnd/scui/src/plugins/test/src/views/test.vue?vue&type=template&id=1f9c2b83&lang.js',
  watchFiles: [
    '/Users/syan/Work/FroutEnd/scui/src/plugins/test/src/index.js',
    '/Users/syan/Work/FroutEnd/scui/src/plugins/test/src/views/test.vue',
    '/Users/syan/Work/FroutEnd/scui/src/plugins/test/src/views/test.vue?vue&type=script&lang.js',
    '/Users/syan/Work/FroutEnd/scui/src/plugins/test/src/views/test.vue?vue&type=template&id=1f9c2b83&lang.js',
    '/Users/syan/Work/FroutEnd/scui/src/plugins/test/src/views/test.vue?vue&type=style&index=0&id=1f9c2b83&scoped=true&lang.css'
  ]
}
```

请教下，如果想使用vue的话，还需要什么操作吗？

**Comment by moonrailgun** [comment]
Hi, 感谢您对`mini-star`的支持: 

我仔细研究了一下`vue`的打包过程。 以下是`vue`引入`mini-star`的最佳实践:

首先，确保 `mini-star` 版本在`1.1.1` 以上。在`1.1.1`版本引入了一个新的配置项[`buildRollupPlugins`](https://ministar.moonrailgun.com/docs/tutorial/guide/ministarrc#buildrollupplugins).

对于`vue`来说, 它的`.ministarrc.js`最小配置应当为:
```js
const vuePlugin = require('rollup-plugin-vue');

module.exports = {
  externalDeps: ['vue'],
  buildRollupPlugins: (plugins) => [
    vuePlugin({
      css: true,
      compileTemplate: true,
    }),
    ...plugins,
  ],
};
```

同时确保在主项目中加载插件的地方有
```js
import {initMiniStar, regDependency} from 'mini-star';

regDependency('vue', () => import('vue'))
// initMiniStar(...)
```

这里有一个示例的vue集成示例项目: [https://github.com/moonrailgun/mini-star/tree/master/example/vue3](https://github.com/moonrailgun/mini-star/tree/master/example/vue3)

稍后我会将`vue`集成的相关文档同步到网站上
